apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-go
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web-go
  template:
    metadata:
      labels:
        app: go-web-go
    spec:
      containers:
      - name: go-web-go
        image: my-image:latest
        ports:
        - containerPort: 8080
